### ISSUE TITLE
Using ckanext-s3filestore with Minio

### ISSUE THREAD

**Issue by ghost** [keitaroinc/ckanext-s3filestore#1]
Hi!

I would like to use the extension for Minio. Although I see that it is in principle possible to use Minio, I do not see anything in the README concerning the setup of the extension for an internal Minio server.

Do you plan to implement that in the future?

Best regards

**Comment by mbocevski** [comment]
You can check out the example within our [docker-ckan repo](https://github.com/keitaroinc/docker-ckan/tree/master/examples/s3filestore). You can check out the config here: https://github.com/keitaroinc/docker-ckan/blob/master/examples/s3filestore/.ckan-env#L32-L37

It's quite straight forward, just fill-in the Minio details where you would normally fill-in the AWS S3 details.
