### ISSUE TITLE
[BUG] Uploads from urls fail to have filenames or extensions

### ISSUE THREAD

**Issue by cslovell** [keitaroinc/ckanext-s3filestore#6]
**Describe the bug**
Assets uploaded from url have no filename. They are saved in s3 as the timestamp only. As an example, if you upload a logo from your local computer as system admin, it will work fine. If you subsequently change the text on the about page, it will not load the file name into the field, and when you save it will save a new object as the logo without a filename, and the logo will appear as an error. 

**ckanext-saml2auth version affected**
v1.0.0

**Expected behaviour**
A file uploaded from a url would have a filename similar to other objects, instead of only having a timestamp with no filename or extension.

**Comment by HristijanVilos** [comment]
Thank you for the feedback. The bug is resolved you can get it from the main branch and soon we will release a version.
