### ISSUE TITLE
Error location constraint 

### ISSUE THREAD

**Issue by pribadihcr** [keitaroinc/ckanext-s3filestore#8]
Hi,

I use ckanext-s3filestore deploy in EKS AWS. The EKS is in region ap-southeast-1, but the S3 bucket in ap-southeast-3.
When access the upload file, I got the following error:
<Error>
<Code>IllegalLocationConstraintException</Code>
<Message>The ap-southeast-3 location constraint is incompatible for the region specific endpoint this request was sent to.</Message>
<RequestId>BCDGPJ0M86NZ7Q8M</RequestId>
<HostId>8wbFgKi3X4vplxJsiZ2HYTLMgsubGQPvSbIlBqglwHWKkgjjqIgElO3XBIYBZKNn2rGgh25YYm8=</HostId>
</Error>

**Comment by HristijanVilos** [comment]
Thank you for your feedback. If this issue is still affecting you please provide more details on how to reproduce the issue.
